services:
  db:
    image: postgres:16-alpine
    container_name: wisp_auth_example_db
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wisp_auth_example
    volumes:
      - pgdata:/var/lib/postgresql/wisp_auth_example_data
    ports:
      - "127.0.0.1:5432:5432"
 
volumes:
  pgdata: